apiVersion: v2
name: linkwarden
description: A Helm chart for LinkWarden - Self-hosted collaborative bookmark manager

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
# renovate: image=ghcr.io/linkwarden/linkwarden
appVersion: "v2.9.2"

keywords:
  - linkwarden
  - bookmark-manager
  - collaboration

home: https://github.com/linkwarden/linkwarden

sources:
  - https://github.com/linkwarden/linkwarden
  - https://github.com/ShivamKumar2002/linkwarden-helm-chart
maintainers:
  - name: Shivam Kumar
    url: https://github.com/ShivamKumar2002
dependencies:
  - name: cluster
    version: 0.1.3
    alias: postgresql
    repository: https://cloudnative-pg.github.io/charts
    condition: postgresql.enabled