{{- if not .Values.linkwarden.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkwarden.fullname" . }}-env-secrets
  labels:
    {{- include "linkwarden.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXTAUTH_URL: {{ .Values.linkwarden.nextAuthUrl | quote }}
  NEXTAUTH_SECRET: {{ .Values.linkwarden.nextAuthSecret | quote }}
  {{- if eq .Values.linkwarden.storage.type "s3" -}}
  SPACES_KEY: {{ .Values.linkwarden.storage.s3.accessKey | quote }}
  SPACES_SECRET: {{ .Values.linkwarden.storage.s3.secretKey | quote }}
  SPACES_ENDPOINT: {{ .Values.linkwarden.storage.s3.endpoint | quote }}
  SPACES_BUCKET_NAME: {{ .Values.linkwarden.storage.s3.bucketName | quote }}
  SPACES_REGION: {{ .Values.linkwarden.storage.s3.region | quote }}
  SPACES_FORCE_PATH_STYLE: {{ .Values.linkwarden.storage.s3.forcePathStyle | quote }}
  {{- end }}
  {{/* If using integrated cnpg postgres, then database url will be set in deployment from the cnpg secret */}}
  {{- if .Values.linkwarden.externalDatabaseUri }}
  DATABASE_URL: {{ .Values.linkwarden.externalDatabaseUri | quote }}
  {{- end }}
  {{- if .Values.linkwarden.emailProvider }}
  EMAIL_FROM: {{ .Values.linkwarden.emailFrom | quote }}
  EMAIL_SERVER: {{ .Values.linkwarden.emailServer | quote }}
  {{- if .Values.linkwarden.emailBaseUrl }}
  EMAIL_BASE_URL: {{ .Values.linkwarden.emailBaseUrl | quote }}
  {{- end }}
  {{- end }}
{{- end }}