
{{- if and (include "linkwarden.ssoEnabled" .) (not .Values.linkwarden.sso.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkwarden.fullname" . }}-sso
  labels:
    {{- include "linkwarden.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $provider, $config := .Values.linkwarden.sso.providers }}
    {{- if not $config.enabled }}
      {{- continue }}
    {{- end }}
    {{- if not $config.customName }}
      {{- fail (printf "Custom name for %s provider cannot be blank" $provider) }}
    {{- end }}
    {{- $providerUpper := upper $provider }}
    {{ printf "NEXT_PUBLIC_%s_ENABLED" ($providerUpper) }}: "true"
    {{ printf "%s_CUSTOM_NAME" ($providerUpper) }}: {{ $config.customName | quote }}
    {{- range $key, $value := $config.secrets }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}